name: Frontend Node.js CI

on:
  push:
    branches: [ staging ]


jobs:
  build:
    runs-on: self-hosted
    environment: staging

    steps:
      - uses: actions/checkout@v3
      - run: node -v
      - run: npm -v
      - name: 'Create env file'
        run: |
          touch ./frontend/my-app/.env
          echo REACT_APP_BASEURL=${{secrets.REACT_APP_BASEURL}} >> ./frontend/my-app/.env
          echo REACT_APP_EMAILJS_OWNER=${{ secrets.REACT_APP_EMAILJS_OWNER }} >> ./frontend/my-app/.env
          echo REACT_APP_EMAILJS_SERVISE=${{ secrets.REACT_APP_EMAILJS_SERVISE }} >> ./frontend/my-app/.env
          echo REACT_APP_EMAILJS_TEMPLATE=${{ secrets.REACT_APP_EMAILJS_TEMPLATE }} >> ./frontend/my-app/.env
      - run: npm --prefix ./frontend/my-app ci
      - run: npm --prefix ./frontend/my-app test
      - run: npm --prefix ./frontend/my-app run build
      - run: rsync -avz -e 'ssh' ./frontend/my-app/build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}