name: Frontend Node.js CI

on:
  push:
    branches: [ staging, develop ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: node -v
      - run: npm -v
      - run: npm --prefix ./frontend/my-app ci
      - run: npm --prefix ./frontend/my-app test
      - run: npm --prefix ./frontend/my-app run build --if-present
      - run: rsync -avz -e 'ssh' ./frontend/my-app/build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}