name: Staging CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  Clone:
    name: Clone git repository
    steps:
      - uses: actions/checkout@v3

  Frontend_CI_CD:
    needs: Clone
    name: Frontend CI/CD
    runs-on: self-hosted
    environment: staging

    steps:
      - uses: actions/checkout@v3
      - run: node -v
      - run: npm -v
      - run: echo ${{secrets.DEPLOY_PATH}}
      - name: 'Create env file'
        run: |
          touch ./frontend/my-app/.env
          echo REACT_APP_BASEURL=${{secrets.REACT_APP_BASEURL}} >> ./frontend/my-app/.env
          echo REACT_APP_EMAILJS_OWNER=${{ secrets.REACT_APP_EMAILJS_OWNER }} >> ./frontend/my-app/.env
          echo REACT_APP_EMAILJS_SERVISE=${{ secrets.REACT_APP_EMAILJS_SERVISE }} >> ./frontend/my-app/.env
          echo REACT_APP_EMAILJS_TEMPLATE=${{ secrets.REACT_APP_EMAILJS_TEMPLATE }} >> ./frontend/my-app/.env
      - run: npm --prefix ./frontend/my-app ci
      - run: npm --prefix ./frontend/my-app test
      - run: npm --prefix ./frontend/my-app run build
      - run: rsync -rvz -e 'ssh' ./frontend/my-app/build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.FRONTEND_DEPLOY_PATH }}

  Backend_CI_CD:
    needs: Clone
    name: Backend CI/CD
    runs-on: self-hosted
    environment: staging

    steps:
      - run: node -v
      - run: npm -v
      - run: npm --prefix ./backend ci
      - name: 'Create env file'
        run: |
          touch ./backend/.env
          echo DB_HOST=${{ DB_HOST }} >> ./backend/.env
          echo DB_DATABASE=${{ DB_DATABASE }} >> ./backend/.env
          echo DB_USER=${{ DB_USER }} >> ./backend/.env
          echo DB_PASSWORD=${{ DB_PASSWORD }} >> ./backend/.env

          echo PORT=${{ PORT }} >> ./backend/.env
          echo SALT_ROUND=${{ SALT_ROUND }} >> ./backend/.env
          echo LINE_CHANNEL_ACCESS_TOKEN=${{ LINE_CHANNEL_ACCESS_TOKEN }} >> ./backend/.env
          echo LINE_CHANNEL_SECRET=${{ LINE_CHANNEL_SECRET }} >> ./backend/.env
          echo JWT_SECRET=${{ JWT_SECRET }} >> ./backend/.env

          echo MQTT_HOST=${{ MQTT_HOST }} >> ./backend/.env
          echo MQTT_PORT=${{ MQTT_PORT }} >> ./backend/.env
          echo MQTT_USERNAME=${{ MQTT_USERNAME }} >> ./backend/.env
          echo MQTT_PASSWORD=${{ MQTT_PASSWORD }} >> ./backend/.env
      - run: npm --prefix ./backend test
      - run: rsync -rvz --exclude=node_modules -e 'ssh' ./backend/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.BACKEND_DEPLOY_PATH }}
      - run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "npm ci --prefix ${{ secrets.BACKEND_DEPLOY_PATH }}"

  Python_CI_CD:
    needs: Backend_CI_CD
    name: Python CI/CD
    runs-on: self-hosted
    environment: staging
    steps:
      - name: 'Create env file'
        run: |
          touch ./drawer/.env
          echo EXPRESS_SERVER=${{ EXPRESS_SERVER }} >> ./drawer/.env
          echo EXPRESS_PORT=${{ EXPRESS_PORT }} >> ./drawer/.env
      - run: rsync -rvz -e 'ssh' ./drawer ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.PYTHON_DEPLOY_PATH }}
      - run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "pip install -r ${{ secrets.PYTHON_DEPLOY_PATH }}/requirements.txt"
